- scionlab/models.py
- scionlab/settings/common.py
- scionlab/settings/development.py
- scionlab/settings/production.py
- scionlab/templates/registration/logged_out.html
- scionlab/templates/registration/login.html
- scionlab/templates/registration/password_change_done.html
- scionlab/templates/registration/password_change_form.html
- scionlab/templates/registration/password_reset_complete.html
- scionlab/templates/registration/password_reset_confirm.html
- scionlab/templates/registration/password_reset_done.html
- scionlab/templates/registration/password_reset_form.html
- scionlab/templates/scionlab/base.html
- scionlab/urls.py
- scionlab/views.py
- scionlab/wsgi.py
Set up the URL routing with some placeholder views for testing.
Add very basic templates (at default path).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/17)
> Add login, logout and password management forms

- requirements.in
- requirements.txt
- scionlab/admin.py
- scionlab/hostfiles/README_standalone.md
- scionlab/hostfiles/Vagrantfile.tmpl
- scionlab/hostfiles/client.conf.tmpl
- scionlab/hostfiles/server.conf.tmpl
- scionlab/management/commands/initialize_root_ca.py
- scionlab/models.py
- scionlab/settings/common.py
- scionlab/settings/x509_cert.default
- scionlab/tests/test_user_as_models.py
- scionlab/tests/test_user_as_views.py
- scionlab/tests/test_vpn_certs.py
- scionlab/util/config_tar.py
- scionlab/util/openvpn_config.py
VPN certificate setup
* generate CA certificate
* generate server certificate
* generate client certificate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/41)
> VPN configuration

- scionlab/tests/utils.py
- scionlab/util/generate.py
- scionlab/util/local_config_util.py
Add a `gen/ia` file containing the IA "file" format.
Modify existing UT to cover this.
Closes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/73)
> 67 add gen ia

- scionlab/models.py
- scionlab/tests/test_user_as_views.py
- scionlab/views/user_as_views.py
If the user AS is attaching with VPN, don't care about the IP address. But if
not using VPN, check that the IP is not local, invalid, etc. and that the
IP version of it is accepted by the attachment point.
Closes #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/70)
> User AS IP input validation.

- scionlab/templates/django_registration/activation_complete.html
- scionlab/templates/django_registration/registration_confirm.html
- scionlab/templates/django_registration/registration_form.html
- scionlab/urls.py
- scionlab/views/registration_view.py
The confirmation page explains that an activation link has been sent by email.
Fixes #81
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/84)
> Add registration confirmation page

- scionlab/fixtures/testtopo-ases-links-extraserv.yaml
- scionlab/fixtures/testtopo-ases-links.yaml
- scionlab/fixtures/testtopo-ases.yaml
- scionlab/fixtures/testtopo-isds.yaml
- scionlab/models/core.py
Add created/modified timestamps to ISD and AS models
Note: diff on fixtures is fairly big because the default formatting seems to have changed in django (files had been generated with previous django version).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/96)
> Add created/modified timestamps to ISD and AS models

- scionlab/fixtures/scionlab_infrastructure.py
- scionlab/models/core.py
- scionlab/scion_config.py
- scionlab/util/archive.py
- scionlab/util/local_config_util.py
- scripts/create-fixture-infrastructure.sh
Import infrastructure nodes
Import user nodes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/86)
> 77 enter infrastructure topology

- scionlab/forms/registration_form.py
- scionlab/templates/django_registration/registration_form.html
- scionlab/templates/django_registration/registration_resend.html
- scionlab/urls.py
- scionlab/views/registration_view.py
Fixes #101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/102)
> Add option to resend activation link

- .circleci/bash_env.sh
- .circleci/config.yml
- .circleci/patches/crit.patch
- .circleci/setup/VPNexistingAS.sh
- .circleci/setup/VPNnewUserAS.sh
- .circleci/setup/coord.sh
- .circleci/setup/create_core_as.py
- .circleci/setup/create_user_as.py
- .circleci/setup/existingAS.sh
- .circleci/setup/minimalInstall.sh
- .circleci/setup/reloadASConfig.sh
- .gitignore
- docker-compose.yml
- scionlab/fixtures/testtopo-ases-links-extraserv.yaml
- scionlab/fixtures/testtopo-ases-links.yaml
- scionlab/fixtures/testtopo-ases.yaml
- scionlab/fixtures/testtopo-isds.yaml
- scionlab/fixtures/testtopo.py
- scionlab/tests/test_user_as_models.py
- scripts/create-fixture-testtopo.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/104)
> Trc update tests

- scionlab/fixtures/scionlab_infrastructure.py
- scionlab/fixtures/scionlab_userASes.py
- scionlab/models/user_as.py
- scionlab/models/vpn.py
- scripts/create-fixture-infrastructure.sh
- scripts/create-fixture-userASes.sh
- scripts/import-scion-coord-users.py
Three CSV files and one fixture are needed:
- `users.csv` to import users and passwords, etc. See #95 
- `connection.csv` directly out of the DB `connection` table
- `scion_lab_as.csv` directly out of the DB `scion_lab_as` table
- `scionlab/fixtures/scionlab-infrastructure.yaml` . See #86 
Closes #79
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/105)
> import user ASes

- scionlab/util/local_config_util.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/108)
> Do not allow ISD loops in beaconing

- scionlab/fixtures/testtopo-ases-links-extraserv.yaml
- scionlab/fixtures/testtopo-ases-links.yaml
- scionlab/fixtures/testtopo-ases-vpn.yaml
- scionlab/fixtures/testtopo-ases.yaml
- scionlab/fixtures/testtopo-isds.yaml
- scionlab/models/user_as.py
- scionlab/settings/common.py
- scionlab/tasks.py
- scionlab/tests/test_api.py
- scionlab/tests/test_huey_taskqueue.py
- scionlab/tests/test_user_as_views.py
- scionlab/tests/utils.py
- scionlab/urls.py
- scripts/init-test-db.sh
Rate limit the deployment frequency per host to one minute. Do not wait a minute before actually running the first update. All updates in the minute following a deployment will be bundled together.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/114)
> Huey cooldown

- scionlab/fixtures/scionlab_infrastructure.py
When creating a hierarchical link, call `create` from(parent) to(child)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/118)
> Create links from parent to child

- scionlab/fixtures/scionlab_infrastructure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/126)
> Create only one side of the link

- scionlab/hostfiles/scion_upgrade_script.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/129)
> The upgrade script uses the service files from scionlab

- scionlab/tests/test_hashers.py
- scionlab/tests/test_huey_taskqueue.py
Issue  #111, failed CI https://circleci.com/gh/netsec-ethz/scionlab/851 and https://circleci.com/gh/netsec-ethz/scionlab/852
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/133)
> Fix flaky tests

- scionlab/templates/scionlab/user.html
Fixes https://github.com/netsec-ethz/scionlab/issues/141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/143)
> Fix overview for VPN setup

- .circleci/config.yml
- .circleci/setup/VPNexistingAS.sh
- scionlab/static/scionlab/style.css
- scionlab/templates/scionlab/user.html
Issue #161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/162)
> Don't wrap IA on User AS page

- scionlab/context_processors.py
- scionlab/templates/scionlab/base.html
Add maintenance mode setting
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/171)
> Add maintenance mode setting

- scionlab/defines.py
- scionlab/util/local_config_util.py
Based on #152 , but for the Go beacon service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/173)
> Propagation interval

- scionlab/scion_config.py
- scionlab/util/local_config_util.py
Also changes the `sciond` Public address to that of the host, instead of `127.0.0.1`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/174)
> Fix quic config

- scionlab/models/core.py
- scionlab/scion_config.py
- scionlab/tests/test_models.py
Fixes #175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/176)
> Do not generate configuration for empty BRs

- scionlab/util/local_config_util.py
Closes-bug: #183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/185)
> Configure logging service configuration to rotate properly

- .circleci/Dockerfile-coord
- .circleci/config.yml
- deploy/Dockerfile-django
- scionlab/templates/scionlab/partials/installation_type_src.html
Don't rely on redirect, directly use the repository url
> Update netsec scion references

- scionlab/templates/scionlab/partials/installation_type_pkg.html
- scionlab/templates/scionlab/partials/installation_type_src.html
- scionlab/templates/scionlab/partials/installation_type_vm.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/222)
> re-add .html to tutorial URLs (sorry for the noise)

- scionlab/templates/scionlab/base.html
> Happy New Year

- scionlab/hostfiles/scionlab-config
> Disable removed services

- .circleci/config.yml
Check VPN connections after package upgrade
> Check VPN connection after update

- scionlab/migrations/0006_pki.py
Configuration version incremented for this update, as all hosts will need to fetch a new configuration.
> Add a bump_config step to migration

- .circleci/config.yml
Removed -local for scmp echo, -srcIA for showpaths.
> Strip removed flags from scmp/showpaths invocation

- .circleci/Dockerfile-scionHost
- .circleci/config.yml
- .circleci/setup/check_tun0_in_topo.py
- scripts/check_tun0_in_topo.py
- scripts/vpn_cleanup.py
Checks that the VPN connections still work after applying the VPN cleanup script
Fixes #251
> scionlab upgrade: vpn cleanup test

- scionlab/tests/test_user_as_models.py
Force attaching clients to one AP until a possible port clash
could happen.
The check was already in place, but the UT didn't have cases with a possible port clash.
Closes #275
> Add UT to force the topology check.

- scionlab/openvpn_config.py
- scionlab/tests/test_vpn_certs.py
Shorten the common name used for the infrastructure hosts by removing the useless default email address.
Also, fix the more generic potential problem of overly long common names e.g. for users with very long email addresses by truncating and appending a UUID -- note that we could just use a unique ID for the common name altogether, the readable names are just for sanity.
Fixes #158
> Fix OpenVPN client common name for infrastructure hosts

- scionlab/views/topology.py
After addition of two non-core ASes to ISD16, the graph was no longer rendering in a desirable way. I have attempted to organize it a bit differently, with limited success. I also took the chance, to slightly polish fonts and colors. Let me know what you think.
> improve network graph after addition of two nodes messed up the layout

- scionlab/hostfiles/Vagrantfile.tmpl
- scionlab/tests/data/test_config_tar/user_as_16.yml
- scionlab/tests/data/test_config_tar/user_as_17.yml
> Bump the minimum vagrant version to 1.8.5.

- scionlab/admin.py
Add various other fields in various other missing places.
> admin: add date joined to user admin list view

- scionlab/admin.py
Add number of ASes to user list, allow sorting and filtering by this column (yes, this is surprisingly complicated).
> admin: add number of ASes to user list

- scionlab/urls.py
- scionlab/views/topology.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/300)
> Add API for getting topology info as JSON

- .circleci/Dockerfile-scionHost
- .circleci/config.yml
Fixes issue #339, run `scion` tool commands from different non-root user
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/345)
> integration tests: Add non-sudoer user to run user commands

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/358)
> ci: fix stale master checkout in update-tests

- scionlab/hostfiles/scionlab-config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/372)
> scionlab-config: log conflicts and skipped files

- static_bin/Dockerfile
- static_bin/scion-pki-darwin-amd64
- static_bin/scion-pki-linux-amd64
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/373)
> SCIONLab biweekly update from upstream, 2021-04-27

- scionlab/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/386)
> search ASes also by ASID

- scionlab/models/core.py
- scionlab/scion/config.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/389)
> write the latest keys for an AS

- scionlab/forms/attachment_conf_form.py
To fix https://github.com/netsec-ethz/scionlab/issues/407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/408)
> Remove unwanted comma suffix

- docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/410)
> deploy: bump caddy image version

- scionlab/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/412)
> admin: add missing search_fields definitions

- scionlab/admin.py
- scionlab/models/vpn.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/417)
> admin: add action to regenerate VPN client key/certificate

- scionlab/templates/scionlab/home.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/419)
> Add SCIONLab paper reference to homepage

- scionlab/templates/scionlab/base.html
- scionlab/templates/scionlab/home.html
Add slack link to footer and to main "about" page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/436)
> Add slack link

- scionlab/management/commands/create_link.py
Just by using the admin webpage, it is extremely difficult to create links among hosts.
This tool should allow easier creation until we build a better admin page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/459)
> Add a create_link management command.

- scionlab/admin.py
- scionlab/models/core.py
- scionlab/tests/test_models.py
If modified, the Coordinator:
- creates a new TRC for the ISD of the modified AS.
- creates new keys and certificates for all the ASes in the ISD.
- **REMOVES** all links that the AS had.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/457)
> Allow modifying is_core via admin interface.

- .circleci/config.yml
Removing a typo that was entered as a pip package.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/471)
> Fix failing CI
