netsec-ethz/scionlab

- scionlab/admin.py
- scionlab/models.py
This should simplify finding the VPN of an attachment point, as well as storing "front end" data for user ASes.
Also, add a `active` flag to a `Link` to allow deactivating a UserAS without removing it from the database's network model (and hence, avoid having to back up the user's configuration somewhere while the AS is inactive).
Note: `UserAS` is a subclass of `AS` so that deletion will cascade properly automatically. On the other hand, `AttachmentPoint` is not a subclass of `AS`, because that would make it annoyingly difficult to turn an AS into an attachment point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/25)
> Add UserAS and AttachmentPoint to data model

- scionlab/admin.py
- scionlab/fixtures/testtopo-ases-links.yaml
- scionlab/fixtures/testtopo-ases.yaml
- scionlab/models.py
- scionlab/tests/test_api.py
- scionlab/tests/test_user_as_models.py
- scionlab/tests/test_user_as_views.py
- scionlab/tests/utils.py
- scionlab/urls.py
- scionlab/util/config_tar.py
- scionlab/util/generate.py
- scionlab/util/http.py
- scionlab/util/local_config_util.py
- scionlab/views/api.py
- scionlab/views/placehoder_view.py
- scionlab/views/user_as_views.py
See #13
Add and populate "secret" field for Host to authenticate requests.
Add view that checks authentication and builds the config tar-ball if necessary.
Due to missing dependencies, not tested with the actual config generation.
No changes made to the config gen to avoid merging.
Depends on #30 and #35.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/38)
> Host config API

- requirements.in
- requirements.txt
This update fixes a low severity security vulnerability (github alert).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/51)
> Bump django from 2.1.2 to 2.1.5

- requirements.in
- requirements.txt
- scion-requirements.in
- scionlab/admin.py
- scionlab/fixtures/testtopo-ases-links.yaml
- scionlab/fixtures/testtopo-ases.yaml
- scionlab/models.py
- scionlab/tests/test_admin.py
- scionlab/tests/test_models.py
- scionlab/tests/test_portmap.py
- scionlab/tests/test_user_as_views.py
- scionlab/tests/utils.py
- scionlab/util/archive.py
- scionlab/util/config_tar.py
- scionlab/util/generate.py
- scionlab/util/local_config_util.py
- scionlab/util/portmap.py
Updated the `local_config_util.py`. As various things had not been working, also includes assorted cleanup and fixes. With this version, the service in an AS seem to startup at least to the point where the certificates are missing (will investigate this further after rebasing the certificate work).
Add explicit BorderRouter object to hold configuration of internal and control address port
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/52)
> Support SCIONLab's current SCION version

- scionlab/hostfiles/scionlab_config.py
- scionlab/tests/test_api.py
- scionlab/tests/utils.py
- scionlab/urls.py
- scionlab/util/config_tar.py
- scionlab/util/http.py
- scionlab/views/api.py
Add python script to fetch and install configuration on scionlab nodes. To reduce dependency issues, only the python standard library is used. Currently this is largely untested; as most operations include some file manipulations etc, testing this (without mocking essentially everything) will require a sandboxed environment of some sort.
Add a `scionlab-config.json` file to the tar ball. This includes the version number and host key/secret for subsequent automatic config requests.
Add API to post the successfully installed version, so the coordinator can keep track of whether the a host needs to be updated.
Changed the API authorization method to use "basic" authentication headers instead of passing parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> scion-configure script, config-info file 

- scionlab/admin.py
- scionlab/auth_backends.py
- scionlab/config_tar.py
- scionlab/fixtures/testtopo.py
- scionlab/fixtures/testuser.py
- scionlab/models/core.py
- scionlab/models/network.py
- scionlab/models/user.py
- scionlab/models/user_as.py
- scionlab/models/vpn.py
- scionlab/scion_config.py
- scionlab/tasks.py
- scionlab/tests/test_admin.py
- scionlab/tests/test_api.py
- scionlab/tests/test_auth_backends.py
- scionlab/tests/test_certificates.py
- scionlab/tests/test_models.py
- scionlab/tests/test_user_as_models.py
- scionlab/tests/test_user_as_views.py
- scionlab/tests/test_vpn_certs.py
- scionlab/tests/utils.py
- scionlab/util/django.py
- scionlab/util/local_config_util.py
- scionlab/views/api.py
- scionlab/views/user_as_views.py
- scripts/init-test-db.sh
Split the models module into four loosely coupled submodules:
- `core`
models representing the SCION network `ISD`, `AS`, `Host`, `Service`, `BorderRouter`, `Interface`, `Link`
- `user_as`
contains `UserAS` and `AttachmentPoint`, i.e. the models responsible for the handling of UserASes. This will be the place where e.g. user-attachmentpoints will be implemented.
- `vpn`
models for the OpenVPN configuration
- `user`
contains the `User` model
I think this will make the code some easier to navigate. In particular, this should make it clearer that `UserAS` and `AttachmentPoint` are modeled on top of the `core` models.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/85)
> Cleanup: split models

- scionlab/admin.py
- scionlab/models/core.py
- scionlab/models/user_as.py
- scionlab/tests/test_certificates.py
- scionlab/tests/test_models.py
- scionlab/tests/test_user_as_models.py
- scionlab/tests/utils.py
- scionlab/views/user_as_views.py
Save models before calling methods relaying on the data graph.
Reload them before modifying in-mem copies.
Closes #89 
There is also a new "Update Core Keys" call in the admin.AS form.
This PR is a bug-fix and only presents one possible way to solve a more generic scenario, in which we have in memory copies of objects that are not persisted yet to the DB, yet some methods rely on the DB being fresh for proper functioning.
It would be nice to establish a set of "rules" for our app, in that we can e.g. only load once and only save once, or e.g. save() and refresh() as objects are changed (maybe using the django cache), etc. Choosing one way of working will help us reason about the data graph easily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Save and load again models to simplify usage.

- scionlab/certificates.py
Certificates cannot expire later than TRC. Add check/upperbound when creating core certificate.
Fixes #94
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/97)
> Upperbound certificate validity period to TRC expiration date

- scionlab/admin.py
- scionlab/forms/fields.py
- scionlab/models/user_as.py
- scionlab/models/vpn.py
- scionlab/openvpn_config.py
- scionlab/tests/test_user_as_models.py
- scionlab/tests/test_user_as_views.py
- scionlab/tests/test_vpn_certs.py
Closes #99 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/100)
> Persist the VPN server IP in the VPN model.

- scionlab/admin.py
In the AS admin view, add a new filter to hide infrastructure or user ASes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/106)
> Admin AS view filters by is infrastructure or not

- scionlab/config_tar.py
- scionlab/models/user_as.py
- scionlab/tests/test_user_as_models.py
Override bind IP for vagrant machine to `10.0.2.15`.
Expose the bind port in Vagrantfile, not public port -- this is an edge case really; if NATed port is different from public port AND VM is used then this needs to happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/123)
> Fix: VM bind ip

- deploy/django-entrypoint.sh
- docker-compose.yml
- scionlab/settings/production.py
Use external DB (from isg) instead of local instance run by
docker-compose in production settings.
Requires two new variables from scionlab.env-file, POSTGRES_HOST and POSTGRES_DB.
Still needs to be tested (either on testing instance or directly while preparing production instance).
TODO: update README, document how to use `docker-compose.override.yaml` to still use a local instance for testing purposes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/125)
> Remove postgres from compose-file, use external DB

- scionlab/admin.py
- scionlab/models/core.py
- scionlab/models/user_as.py
- scionlab/tests/test_user_as_models.py
- scionlab/tests/utils.py
One BR takes care of the interfaces not talking to children ASes.
The rest of the interfaces are spread using border routers, so that
no border router has more than 10 interfaces. The number 10 is an
argument to a function and can be changed.
Just noticed that the condition to split the interfaces being "children" or not, is not enough, as there are cases where an AP has a child which is not a user AS. It is not a bug, but it should be changed eventually to avoid this child ASes to change interface when user ASes are reconfigured.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/128)
> In the APs, split the border routers.

- docker-compose.yml
Volumes need to be mounted with the `:z`/`:Z` options, otherwise we'll see "permission denied" (even for root) inside the container.
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/127)
> Fix docker volume mounts for SELinux

- scionlab/models/user_as.py
- scionlab/tests/test_huey_taskqueue.py
- scionlab/tests/test_user_as_models.py
Before, the deployment task was started while the transaction was still
ongoing. The task checks at the beginning whether it should actually do
run the deployment based on the version number in the DB.
If the task starts up quickly it would abort immediatly, because the
version bump has not been commited to the DB yet.
Fixed by starting the task in transaction.on_commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/130)
> Fix race-condition in deployment task start

- scionlab/admin.py
- scionlab/models/vpn.py
- scionlab/openvpn_config.py
Use the host id in the common name (which needs to be unique per VPN
server); this allows to use one VPN client per host.
We may want to make use of this soon to configure some of the VPN
tunnels used in the infrastructure ASes directly in the coordinator,
instead of having random copy-pasted config files.
Note having multiple: clients per host would require to additionally
include the VPN Client id but would also require a bunch of other
changes (e.g. file couldn't just be called `client.conf`).  We don't
currently need this.
Make admin for VPN a bit friendlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/132)
>  Enable multiple VPN clients in infra ASes

- scionlab/hostfiles/scionlab-config
Closes #134 
Also fixes two other issues for user ASes:
- When going from having VPN to not having, the script would fail trying to remove `/etc/openvpn/client.conf`
- When going from not VPN to VPN, the script would start SCION before having VPN, letting the BR fail to bind to the VPN interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/135)
> Scionlab config sudo fix

- scionlab/models/user_as.py
- scionlab/scion_config.py
Use an explicit order_by when iterating over BRs/Services, to get predictable service IDs.
This was previously missing because I had misunderstood djangos query documentation; for `first`, the order does default to pk, but for other queries there is no default order.
Note: the issue is surprisingly tricky to reproduce locally because when loading data from a fixture into a local postgres instance, it will have the rows in the "correct" `id` order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/138)
> Fix order of BR and service IDs in topology.json

- scionlab/scion_config.py
E.g.
```
"BeaconService": {
"bs17-ffaa_0_1103-1": {
"Addrs": {
"IPv4": {
"Public": {
"Addr": "86.119.37.2",
"L4Port": 31041
},
"Bind": {
"Addr": "10.0.235.43",
"L4Port": 31041
}
}
}
}
},
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/140)
> Generate topology with Bind for services when needed

- scionlab/management/commands/export_zonefile.py
- scionlab/models/core.py
Adds a management command to export all hosts to a RAINS zonefile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/139)
> Add management command to export hosts as zonefile for RAINS

- scionlab/scion_config.py
Use `bind_ip` in the `"Bind"` section for services only if the `internal_ip` matches `public_ip`; the reason is that the `bind_ip` is only really defined for the `public_ip`. If the `internal_ip` is different from `public_ip`, e.g. if it's 127.0.0.1 or identical to `bind_ip`, then it doesn't make sense to use `bind_ip`.
We'd need an internal_bind_ip to represent this correctly -- luckily we don't seem to need this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/147)
> Use bind IP for services only if appropriate

- scionlab/defines.py
- scionlab/util/local_config_util.py
Use 60s beaconing interval on all nodes except APs to reduce CPU load
incurred by the (core-AS) beaconing.
Keep frequency high on APs to allow quick startup for UserASes.
Questions:
- should we rather make the distinction core/non-core?
- also change `RegisterTime`?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/152)
> Reduce beaconing frequency except on APs

- scionlab/hostfiles/Vagrantfile.tmpl
Currently we rely on a default Vagrant provider set by OS or user.
As we only support VirtualBox, we need to explicitely state it in
the Vagrantfile so it runs correctly on systems with other providers.
Closes-Bug: #165
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/166)
> Set Vagrant provider explicitely

- scionlab/tasks.py
The infrastructure's `authorized keys` contain already the `command=sudo scionlab-config` .
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/172)
> call sudo scionlab-config

- scionlab/hostfiles/Vagrantfile.tmpl
* Remove useless forwarded UDP port 31042
* Add comments to clarify why the other ports are forwarded (as documentation for us and for users)
* Disable logging serial port by default
By default this logs to a file `ubuntu-xenial-16.04-cloudimg-console.log`, which is (usually) just clutter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/202)
> Vagrantfile: remove unneeded port forwards and disable serial port logging

- scionlab/views/user_as_views.py
We've observed that the order of ASes in the list page sometimes changes,
as it is just the order in which the DB returned the entries.
This fix is only for cosmetics, with only 5 ASes it would not be a real
problem to find an AS even if it the order would change on every
refresh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/201)
> Order Entries in User-AS List

- scionlab/fixtures/testdata.yaml
- scionlab/fixtures/testtopo.py
- scionlab/models/core.py
- scionlab/scion_config.py
- scionlab/scion_topology.py
- scionlab/tests/data/test_config_tar/host_4.yml
- scionlab/tests/test_config_tar.py
Currently the coordinator is not generating any systemd configuration for BWtester. Its existence introduces multiple classes of services running on the hosts
- static services running always (like dispatcher)
- instantiated services running always (like daemon)
- instantiated services running based on the config (like border routers)
- static services running based on the config (like bandwidth tester)
Having the first 3 already covered, this patch introduces support for the last class. Apart from this, it removes references to the "Service.PP" which has been deprecated some time ago.
Please note this patch do not introduce generating supervisord configuration for the 4th class of the services, mainly because in the current state bwtestserver is not meant to be run on non-infrastructure …
> Generate systemd configuration for BWtester

- scionlab/settings/common.py
In order to allow modification of the arbitrarily big entities
the DATA_UPLOAD_MAX_NUMBER_FIELDS needs to be increased from the
default value of 1000.
Closes: #214
> Increase DATA_UPLOAD_MAX_NUMBER_FIELDS to 10000

- scionlab/models/core.py
When deleting a border router or a service it turns out we are
trying to iterate over a list containing the element which is being
removed. This causes creating a DB lookup over non-existing element
what in effect crashes the engine.
This change workarounds it by catching this case and returning an
arbitrary ID for this service. As we are not showing it in the UI
anymore (because it's being deleted), it does not have an visible
impact.
Close: #216
> Check for NULL when iterating over routers/services

- scionlab/openvpn_config.py
Newly created server certificates were missing X509v3 Key Usage `Key Encipherment`
Expected value for field `X509v3 Key Usage`: `Digital Signature, Key Encipherment`
Previous value for field `X509v3 Key Usage`: `Digital Signature`
Symptoms:
Clients fail to connect with message
```
scionlab-ffaa-1-0 ovpn-client[11]: Validating certificate key usage
scionlab-ffaa-1-0 ovpn-client[11]: ++ Certificate has key usage  0080, expects 00a0
scionlab-ffaa-1-0 ovpn-client[11]: ++ Certificate has key usage  0080, expects 0088
scionlab-ffaa-1-0 ovpn-client[11]: VERIFY KU ERROR
scionlab-ffaa-1-0 ovpn-client[11]: TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
scionlab-ffaa-1-0 ovpn-client[11]: TLS Error: TLS object -> …
```
> Add missing key usage key_encipherment to vpn server certificate

- scionlab/config_tar.py
- scionlab/tests/data/test_config_tar/user_as_16.yml
- scionlab/tests/data/test_config_tar/user_as_17.yml
- scionlab/tests/utils.py
Virtualbox fails to create configuration directories on macOS and Windows, since it is using the vmname containing colons
Use the filename format
Fixes issue #241
> Fix VM provider not supporting IA in box name

- .circleci/docker-compose.yml
>You can mount a relative path on the host, that expands relative to the directory of the Compose configuration file being used
The context only applies to the build section.
> Fix run mount path in CI

- scionlab/admin.py
- scionlab/config_tar.py
- scionlab/hostfiles/scionlab-config
- scionlab/tests/data/test_config_tar/user_as_19.yml
- scionlab/tests/test_api.py
- scionlab/urls.py
- scionlab/views/api.py
The functionality of the API is unchanged, but the content returned in the config-tarfile is not compatible with older versions. Bumping the API version number will ensure that only updated clients can fetch data once the coordinator has been updated.
* Add `api/v2/` URLs
* Add view for old URL pattern that responds with "410 Gone"
* Use `api/v2/` URLs in `scionlab-config`
* Remove backwards compatibility logic in VPN client config filenames
* Add `--version` flag to `scionlab-config` (version is "2.0, api/v2, March 2020")
Closes #248
> Add version number to API

- scionlab/settings/common.py
- scionlab/static/scionlab/style.css
- scionlab/templates/scionlab/base.html
- scionlab/tests/test_maintenance_mode.py
This helps for the next planned maintenance, where we mainly want to disallow changes on user ASes.
As we may want to keep maintenance mode on for more than a few minutes, it makes sense to at least show the home page.
Allowing access to the API to fetch host configuration is ok here as it's a read-only operation. Setting the deployed config version is obviously not read only, but seems low risk as it's not directly used.
This may simplify the update procedure, as the maintenance mode can be kept on until all the infrastructure machines are updated.
> Allow accessing home view and API in mainteance mode

- .circleci/config.yml
Removing DB files is now part of package upgrade scripts. No longer should/have to explicitly purge this.
Now with a branch name that should trigger the upgrade tests.
> CI: removing DB files is now part of package upgrade scripts

- deploy/Dockerfile-django
Seems to break build in docker-compose in production (with old?? docker version).
> Dockerfile-django: remove unneeded AS directive that breaks build in production

- scionlab/hostfiles/scionlab-config
Simply stop the scionlab target and remove all its symlinks after.
Then enable the new services received from the Coordinator.
> Stop services and remove symlinks instead of disable

- scionlab/hostfiles/scionlab-config
Fix simple bug occurring if there is no VPN client configured. Was always showing the warning "VPN could be unready. SCION may fail to start." and would always wait for 5 seconds.
> Fix spurious warning about VPN when no VPN configured

- scionlab/models/user_as.py
- scionlab/settings/common.py
- scionlab/settings/development.py
- scripts/port_clash_fixup.py
Two things:
- fix the bug creating port clashes: force getting a new port when reattaching the user AS to an AP
- one time script to print and fix the clashes
Closes #271
> port clashes

- scionlab/config_tar.py
- scionlab/hostfiles/scionlab-config
* scionlab-config: properly handle 204 no content
Also slightly reshuffle function calls for stop/start scion for clarity.
*  On coordinator, only return 204 no content for detached hosts (i.e. for hosts for which the associated AS has been deleted). 
For hosts that simply have no services configured, we can (and will) still create a sensible end host configuration and it makes sense to allow installing this.
Fixes #270
> Fix handling empty config

- scionlab/models/core.py
- scripts/fed4fire-scionlab.yml
- scripts/import_topo.py
Add a very ad-hoc script to import the topology for GEANT/DFN/fed4fire from a yaml file.
The input yaml file is a (manually) extended / modified version of a the yaml dump from https://fin-ger.github.io/scionlab-fed4fire-topology/
> Import new GEANT/DFN/fed4fire topology

- scionlab/scion_config.py
Accidentally wrote out core AS certificate instead of certificate chains.
> Fix writing certificate directory for core ASes

- scionlab/forms/attachment_conf_form.py
- scionlab/templates/scionlab/partials/user_as_form_script.html
The JS attempts to hide the div-containers holding the IP input fields,
when the VPN option is enabled.
The div container no longer had the class that the JS code was looking
for.
This was caused by the update to django-3, in particular the update
django-crispy-forms.
Fixed by adding an explicit 'hidable' class on the appropriate div.
Fixes #291
> Fix hiding IP fields in user AS form

- scionlab/hostfiles/Vagrantfile.tmpl
- scionlab/tests/data/test_config_tar/user_as_16.yml
- scionlab/tests/data/test_config_tar/user_as_17.yml
Avoid the creation of the `ubuntu-xenial-16.04-cloudimg-console.log` file by redirecting serial output to `/dev/null` instead of disconnecting the serial port.
Tested in Ubuntu and macOS.
Closes #294 
Relates to #202 
Relates to #293
> Virtualbox 6 UART fix

- scionlab/forms/registration_form.py
- scionlab/tests/test_registration.py
* Fix form in UserRegistrationResendView
Quirky, see comment on RegistrationResendForm.
Was probably broken since updating the django-registration dependency from 3.0 to 3.1.
* Add tests for resending activation email and split up registration test into smaller units.
Fixes #304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/305)
> Fix re-sending activation email

- scionlab/forms/attachment_conf_form.py
- scionlab/forms/user_as_form.py
- scionlab/models/user_as.py
- scionlab/templates/scionlab/user_as_details.html
Links between user ASes and to non-attachment point ASes can only be created/modified by admins. For they user, they are read-only and so we call them "fixed links".
All applicable link types are allowed, i.e. Infra AS - User AS and User AS - User AS for both peering and provider links (in either direction). Note: core links are not an option, user ASes are not core.
Existing fixed provider links (regardless of which direction) disallow the user from changing the ISD for this user AS.
As all other changes through the admin panel, changes to these links do not trigger an automatic config deployment for the affected hosts.
The user sees a list of the fixed links. Example:
Fixes #299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add support for fixed links to non-AP ASes

- .circleci/config.yml
- .flake8
- README.md
- flake8.ini
- scionlab/config_tar.py
- scionlab/defines.py
- scionlab/hostfiles/scionlab-config
- scionlab/scion/config.py
- scionlab/scion/topology.py
- scionlab/tests/data/test_config_tar/host_4.yml
- scionlab/tests/data/test_config_tar/user_as_18.yml
- scionlab/tests/data/test_config_tar/user_as_19.yml
- scionlab/tests/data/test_config_tar/user_as_20.yml
- scionlab/tests/test_api.py
- scionlab/tests/test_archive.py
- scionlab/tests/test_config_tar.py
- scionlab/tests/test_scionlab-config.py
- scionlab/tests/utils.py
- scionlab/urls.py
- scionlab/util/archive.py
* Create flatter configuration directory hierachy (see #307)
* the root `/etc/scion` contains all `*.toml` service configuration files, the `topology.json` file and the `certs/`, `keys/` (and in the future `crypto/`)
* the scionlab-config.json file now contains a list of files generated by the coordinator, with checksum. This allows the scionlab-config script to know which files to remove/replace in an update. The checksum allows the scionlab-config script to avoid trampling over files modified by the user. In the configuration tar file, the configuration files are now stored under their full installation path (e.g. `etc/scion/topology.json`).
* the scionlab-config.json file also contains a list of "managed" services. This allows us and SCIONLab users to enable services outside of the …
> Flat configuration directory hierarchy

- scionlab/templates/scionlab/home.html
On the occasion of the ICNP2020, adding a link to the registration form to join our infrastructure.
~~This change should be temporary, and removed after the ending of ICNP2020.~~
This change is no longer temporary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/311)
> add a link to our ICNP2020 infra node registration form

- scionlab/models/core.py
- scionlab/tests/test_models.py
The `PortMap` returned by the `Host` now also covers the services this host has.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/317)
> Host.get_port_map includes now services' ports

- .circleci/config.yml
- scionlab/hostfiles/server.conf.tmpl
- scionlab/openvpn_config.py
- scionlab/tests/data/test_config_tar/host_4.yml
Add --local to openvpn server config to ensure that the server binds to
a specific address and always responds from the correct local address;
when binding to all interfaces, the source address depends on routing
which might not be what we want.
Closes #319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/320)
> vpn: add --local to server config 

- scionlab/defines.py
- scionlab/scion_config.py
- scionlab/views/topology.py
The prometheus port of BR and CS could clash.
The BR's prometheus port is set to internal port + 400. Now if the BR's
internal port is 30054, the prometheus port will be 30454 wich is also
the CS's fixed prometheus port.
Using the BR's control port as basis of the prometheus port calculation
fixes this problem (temporarily, I hope), because the range of the
control port overlaps with the CS's service (30254) port and so avoids it.
This leaves all other prometheus port assignments unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/321)
> Fix prometheus port clashes BR vs CS

- scionlab/models/core.py
- scionlab/tests/test_models.py
Similar to previous fix in #321; as the BR's control port could clash
with the sciond port (UDP vs TCP so no problem), the corresponding
prometheus ports would also clash.
So we just avoid the SD port when assigning BR control ports.
This time, actually extend the tests to verify that this works as expected, like I should have done half an hour ago.
Again, this is a hopefully temporary fix (and hence the clunky test code).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/322)
> Fix prometheus port clashes BR vs SD

- deploy/Caddyfile
Add https:// to redirect. Without scheme, the redirect was interpreted
as URI on the same server, leading to a redirect loop.
Note that there is unfortunately no test for this right now, as it would
require faking host names etc. I'm confident this fix works because it's
already running in "production".
Enable logging for the scionlab.org site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/327)
> caddy: fix redirect to www. subdomain

- scionlab/scion/config.py
- scionlab/tests/utils.py
Small fixes for flake and unittests after merging #309 prematurely.
Note: as I was expecting the integration tests to be failing after #309,
I merged despite the big red cross warning of failing tests -- I whould
of course have checked that the basic tests _are_ passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/330)
> Fixup broken tests after #309

- scionlab/hostfiles/scionlab-config
- scionlab/tests/test_scionlab-config.py
We explicitly create empty directories in the configuration archive in
two places:
- openvpn ccd/ must exist, otherwise the server refuses to start
(this usually doesn't make any difference as no client can connect if
there is nothing in the ccd/)
- crypto/ca/clients/ must exist, otherwise the CS refuses to start
(new CPPKI). As we don't put anything into this directory, we have to
ensure it is created.
The scionlab-config script was previously explicitly only extracting
specific files listed in the configuration info "manifest" from the
archive. Now it extracts everything, after checking that the archive
only contains the expected files plus possibly some directory entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix extract empty directories in scionlab-config

- .dockerignore
The .dockerignore file does not support inline comments, only comment lines.
So the run/ was previously not ignored as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/335)
> Fix .dockerignore comment

- scionlab/scion/config.py
Simple, stupid bad indent (and missing tests).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/337)
> Fix config generation for hosts without CS

- scionlab/models/core.py
- scionlab/scion/topology.py
- scionlab/tests/utils.py
In order to get rid of the `control_port` and `internal_port` fields
for the routers, we will want to determine these ports based on the
routers `instance_id`.
The `instance_id` had previously been treated specially and was only
added when fetching the objects to generate the AS topology; this was
done because determining the id based on the PK order is normally
expensive, but we can cheaply annotate the objects when we load all
BorderRouter/Services of an AS anyway.
This change turns the `instance_id` into a "normal" `cached_property` on
BorderRouter/Service, so it is always available. We still do the
annotation optimisation when fetching the objects while generating the
AS topology, by simply overriding the `instance_id` entry in the
object's `__dict__` -- this is exactly how the …
> instance_id property on BorderRouter/Service

- scionlab/hostfiles/scionlab-config.service
Use absolute path to scionlab-config executable in scionlab-config.service.
This is enforced by systemd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/351)
> Use absolute path in scionlab-config.service

- .dockerignore
Accidentally removed in #355. The .circleci subdirectory is unnecessary
for the production docker image builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/357)
> dockerignore: add .circleci back

- scionlab/scion/config.py
- scionlab/tests/data/test_config_tar/host_1.yml
- scionlab/tests/data/test_config_tar/host_16.yml
- scionlab/tests/data/test_config_tar/host_17.yml
- scionlab/tests/data/test_config_tar/host_4.yml
- scionlab/tests/data/test_config_tar/user_as_18.yml
- scionlab/tests/data/test_config_tar/user_as_19.yml
- scionlab/tests/data/test_config_tar/user_as_20.yml
Remove obsolete rev_ttl and rev_overlap options from the generated CS config file.
These options are still accepted but ignored by the current version of
the CS. This was cleaned up in the SCION upstream and will no longer be
recognised in the configuration file (https://github.com/scionproto/scion/commit/4234a5869fdde41abe0e007d29aadc37d2af6b2f).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/360)
> Remove obsolete rev_ttl and rev_overlap options

- scionlab/hostfiles/scionlab-config
- scionlab/tests/test_scionlab-config.py
In the postinst-script of the scionlab.deb debian package, we currently invoke `scionlab-config` with `--force`; the idea was that we want to ensure a clean state during package upgrades. Also, `--force` was previously the only way to silence prompts. However, this hinders tinkering with the configuration files as modifications are frequently overwritten (albeit with a backup) somewhat unexpectedly.
We will remove the `--force` from the invocation in the package postinst script and instead default to "keep" the locally modified files.
Changes:
- install skipped files (i.e. files with conflicting edits for which the user chose to _keep_ the local version) with a `.confnew` suffix for future reference (i.e. to diff).
- make "keep" the more conservative default in prompt
- add option …
> scionlab-config: default to "keep" in prompts, add option to silence prompts

- scripts/deactivate_dormant.py
Add script to deactivate dormant User ASes. An AS is deactivated if:
- the owner has not logged in for at least one year
- it is on the list of inactive user ASes, exported from the monitoring
system.
Created by inspecting the router_interface_up on the attachment
points.
Deactivating dormant ASes reduces the load on the attachment points. If
the user ever comes back, re-activating the AS can be done with a big,
green "Activate" button in the scionlab website.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/369)
> script: deactivate dormant

- .circleci/config.yml
Crpytography wheel cannot be easily installed with an old version of pip
(does not support the required wheel tag and whatever that entails).
Update pip before installation to fix this, bump cache key version to
force running this.
Accidentally broken in #366 -- this pip update was there initially but I
removed it later because I thought it was not needed in the newer python
docker image. Due to the cache, the later CI runs did not encounter the
problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/370)
> ci: fix python setup

- scionlab/fixtures/testdata.yaml
- scionlab/fixtures/testtopo.py
- scionlab/models/core.py
- scionlab/scion/topology.py
Previously we've had even more minimal support for SIG topology entries
only in User ASes.
Add support for an explicit SIG Service object, to allow configuring the
same thing in the SCIONLab infrastructure ASes.
As before, this is only concerned with adding a topology entry so that
the routers are able to resolve the SIG service address -- actually
configuring the SIG itself is still out of scope and is done manually on
each host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/374)
> Add minimal SIG topology entry support

- scionlab/admin.py
- scionlab/tests/test_admin.py
Add appropriate exclude parameter when invoking full_clean,
analogous to the original ModelForm._post_clean.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/375)
> admin: fix ValidationError handling for LinkAdminForm

- .circleci/config.yml
- scionlab/settings/common.py
- scionlab/urls.py
Add general and permanent URL for topology in case we replace the PNG image with something else in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/376)
> Add redirect for topology

- requirements.txt
Bump django from 3.2 to 3.2.4
Bump urllib3 from 1.26.4 to 1.26.5
Bumped manually because dependabot messes up (removes typing-extensions
dependency, not an idea why). See corresponding dependabot PRs:
Closes #377, closes #379
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/380)
> Bump django and urllib3

- scionlab/fixtures/testdata.yaml
- scionlab/models/user_as.py
- scionlab/tests/data/test_config_tar/host_4.yml
- scionlab/tests/test_user_as_models.py
- scripts/deactivate_dormant.py
- scripts/merge_ap_routers.py
Use a single router process in attachment points, vs previously
distributing the interfaces over many routers with max 12 interfaces
each. This was a workaround for some issue in an old version of the
router. Now, this is no longer necessary and running many instances is
harmful for the system's performance.
Remove the automatic splitting of interfaces over many routers.
Once this change is deployed, the script `merge_ap_routers` should be
run to merge and clean up the left router instances.
One notable caveat: the router, as it is implemented now, uses a
blocking write, which can in this configuration potentially slow down
processing of the downstream traffic to the slowest User AS link speed.
This should be fixed in the router implementation, hopefully soon.
---
This change is [<img …
> Use a single router process in attachment points

- scionlab/scion/config.py
- scionlab/tests/data/test_config_tar/host_1.yml
This is no longer used/needed in the current version of SCIONLab.
In the next version, these settings will no longer be accepted in the
configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/384)
> Remove unused renewal_db and ca/client from config

- scionlab/settings/common.py
This setting is new in django 3.2. Setting it to the default AutoField
does not change the schema, but is required to silence a warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/385)
> Set DEFAULT_AUTO_FIELD to AutoField

- scionlab/models/core.py
- scionlab/scion/config.py
- scionlab/scion/trcs.py
- scionlab/tests/test_trc.py
Fix issue with overwritting certificate with random version of certificate when updating TRC, after changes to the set of core ASes
Add regression test and unit test checking the new behavior of bundling the latest cert version and not some cert version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/387)
> Fix issue when updating TRC, deleting or adding core AS

- .circleci/config.yml
Cached venv is not compatible with python installation in updated images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/394)
> ci: bump cache keys to avoid old venv cache

- scionlab/admin.py
Remove left-over registration for trigger_config_deployment action,
which was removed in #313.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/405)
> admin: remove left-over reference to obsolete action

- scripts/recreate-test-results.sh
`manage.py test -s` does not work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/415)
> test runner is no longer nose, change silent argument to -v0

- scionlab/config_tar.py
- scionlab/scion/config.py
- scionlab/tests/data/test_config_tar/host_1.yml
- scionlab/tests/data/test_config_tar/host_16.yml
- scionlab/tests/data/test_config_tar/host_17.yml
- scionlab/tests/data/test_config_tar/host_4.yml
- scionlab/tests/data/test_config_tar/user_as_18.yml
- scionlab/tests/data/test_config_tar/user_as_19.yml
- scionlab/tests/data/test_config_tar/user_as_20.yml
Enable DRKey in all CSs.
Because of PR https://github.com/netsec-ethz/scion/pull/104 that adds DRKey usage to COLIBRI, the configuration of DRKey is no longer optional.
Make the Coordinator write configuration for the SD and CS:
- SD must configure a drkey DB
- CS configures a drkey DB, a certificate file, a key file and a delegation list (for the "colibri" protocol)
Still TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/403)
> Enable DRKey everywhere

- .circleci/config.yml
CI runs the upgrade test by building `master`. To do so, it runs
```shell
git checkout master
git pull --ff-only  # may be stale
```
But it could happen that `master` was already checked out in `.git` and recover by the cache, and thus the branch will be local only (or whatever the cache had) and `git pull` will fail.
Instead run
```shell
git checkout --force -B master --track origin/master
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/422)
> checkout master tracking it CI upgrade test

- .circleci/config.yml
After CI plan change, reenable docker layer caching feature to speed up docker image (re)building
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/428)
> Reenable docker layer caching

- scionlab/templates/scionlab/base.html
The Slack link shown in the webpage is expired. The new one is valid for 30 days only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scionlab/478)
> Renew slack link (30 days only).
